### PR TITLE
fixed cmake install

### PR DESCRIPTION
**Pull request by staxfur**
Fixed the install as discussed. I have push access into jupiter-xeus, but not into your fork! So it's a PR.

### CODE REVIEW

**Comment by certik** [comment]
Thanks! It should work if you push directly to this branch. But a PR also works. Thanks for fixing it! Looks great.

**Comment by staxfur** [comment]
No, this is on your fork and i'm not contributor here, next time you need to create a branch on the upstream repository and not your fork / copy. @certik

**Comment by certik** [comment]
No this is correct --- I checked that "maintainers can contribute to the branch". If you push to the branch, it should work like this:
```
git push git@github.com:certik/cpp-terminal split
```
You can't push to other branches, but you can push to this branch.

Unless something is broken, but the above is how it normally works.

**Comment by staxfur** [comment]
Hmm, I tried pushing to this branch first, but it gave me a permission denied error. So I don't know what's wrong here. Maybe a bug in my git client?

**Pull request merged**
